version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # Проксируем порт 4200 из контейнера на порт хоста
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"